"""Multinomial logistic-regression adapter for the shared experiment runner.

This module contains model-specific fitting, probability prediction and
checkpoint handling. Participant splits, nested CV, label prediction
(``argmax`` of the ordered probabilities), metrics and result writing are
centralised in ``run.py`` and ``results.py`` so every model follows the same
experimental procedure.
"""

from __future__ import annotations

import pickle
import warnings

import numpy as np
from sklearn.exceptions import ConvergenceWarning
from sklearn.linear_model import LogisticRegression

from data import fit_standardizer


def fit(train, validation, *, value, seed, settings, sample_weight, epochs=None):
    """Fit scaling and LR on train only; the runner scores validation separately."""
    if epochs is not None:
        raise ValueError("LR does not use a refit epoch count")
    if not np.isfinite(value) or value <= 0:
        raise ValueError("C must be finite and positive")
    if set(settings) != {"solver", "max_iter", "tol"}:
        raise ValueError("LR settings must contain solver, max_iter and tol")
    if settings["solver"] != "lbfgs":
        raise ValueError("The agreed multinomial LR solver is lbfgs")
    if not np.array_equal(np.unique(train.y), np.arange(4)):
        raise ValueError("LR training requires all four class IDs: 0, 1, 2, 3")
    weights = np.asarray(sample_weight, dtype=np.float64)
    if (weights.shape != train.y.shape or not np.all(np.isfinite(weights))
            or np.any(weights <= 0) or not np.isclose(weights.mean(), 1.0)):
        raise ValueError("Training sample weights must be positive, aligned and mean-one")

    scaler = fit_standardizer(train.X)
    model = LogisticRegression(C=float(value), random_state=int(seed), **settings)
    try:
        with warnings.catch_warnings():
            warnings.simplefilter("error", ConvergenceWarning)
            model.fit(scaler.transform(train.X), train.y, sample_weight=weights)
    except ConvergenceWarning as error:
        raise RuntimeError(
            "LR did not converge; this fit is incomplete. Review the convergence "
            "settings before continuing the agreed experiment."
        ) from error
    if not np.array_equal(model.classes_, np.arange(4)):
        raise RuntimeError("LR probability columns must follow class IDs 0, 1, 2, 3")
    return {"model": model, "scaler": scaler}, {
        "best_epoch": None, "iterations": int(np.max(model.n_iter_))
    }


def predict_proba(state, X):
    """Scale X and call the fitted model's predict_proba method.

    The shared runner converts these ordered probabilities to predicted labels
    with argmax, which is equivalent to ``model.predict`` for this classifier.
    """
    model = state["model"]
    if not np.array_equal(model.classes_, np.arange(4)):
        raise ValueError("Saved LR class order is invalid")
    return np.asarray(model.predict_proba(state["scaler"].transform(X)), dtype=np.float64)


def serialize(state):
    """Include the training-only scaler so reloaded predictions are identical."""
    return pickle.dumps(state, protocol=pickle.HIGHEST_PROTOCOL)


def deserialize(payload):
    """Load only checkpoints generated by your own trusted run: pickle executes code."""
    state = pickle.loads(payload)
    if not np.array_equal(state["model"].classes_, np.arange(4)):
        raise ValueError("Saved LR class order is invalid")
    return state
